########### CONFIG ###########
baseURL = "https://vidify.org/"
languageCode = "en"
title = "Vidify"
theme = "navigator-hugo"

enableRobotsTXT = true
googleAnalytics = "UA-162662877-1"
enableGitInfo = false

[markup.goldmark.renderer]
# Embedding raw HTML inside markdown isn't a problem because there isn't any
# user-generated content.
unsafe = true

# Site parameters
[Params]
logo = "images/logo.png"
dateFormat = "Jan _2, 2006"
enableBlogImages = false

# Multiple languages
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
[[Params.langsList]]
code = "es"
name = "Español"
[[Params.langsList]]
code = "en"
name = "English"
[[Params.langsList]]
code = "nl"
name = "Nederlands"

[[Params.langsList]]

code = "zh-CN"

name = "Chinese-Simplified"


########### LANGUAGES ###########
[Languages]
[Languages.en]
weight = 1
languageCode = "en-us"
title = "Vidify"
description = "Play live music videos anywhere."
tags = "music videos, broadcast, live, real time, spotify, android, TV, windows, linux, mac os, television"
dateFormat = "January 2, 2006"

[Languages.es]
weight = 2
languageCode = "es-es"
title = "Vidify"
description = "Reproduce videoclips en directo y en cualquier sitio."
tags = "videoclips, en directo, broadcast, real time, spotify, android, TV, windows, linux, mac os, videos, television"
dateFormat = "2 January 2006"

[Languages.nl]
weight = 3
languageCode = "nl-nl"
title = "Vidify"
description = "Speel live muziekvideo's overal af"
tags = "muziekvideo's, uitzenden, live, real-time, spotify, android, TV, windows, linux, mac os, televisie"
dateFormat = "2 January 2006"

[Languages.zh-CN]
weight = 4
languageCode = "zh-CN"
title = "Vidify"
description = ""
tags = ""
dateFormat = ""


########### MENU ###########
# The Themefisher font is used for the icons:
# https://github.com/themefisher/themefisher-font
# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "home"
url     = "/"
weight  = 1
[[menu.nav]]
name    = "wiki"
url     = "wiki"
weight  = 2
[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 3
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 4
[[menu.nav]]
name    = "github"
url     = "https://github.com/vidify"
weight  = 5

# Footer Service Menu
[[menu.github]]
name    = "vidify"
url     = "https://github.com/vidify/vidify"
weight  = 1
[[menu.github]]
name    = "audiosync"
url     = "https://github.com/vidify/audiosync"
weight  = 2
[[menu.github]]
name    = "vidifyorg"
url     = "https://github.com/vidify/vidify.org"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "gettingstarted"
url     = "/wiki/#wiki"
weight  = 1
[[menu.quicklink]]
name    = "faqs"
url     = "/wiki/faq/"
weight  = 2
